config/routes.rb
Rails.application.routes.draw do
  # get 'blog_exams/index'
  # get '/blog_exams', to: 'blog_exams#index'
  resources :blog_exams do
  collection do
    post :confirm
  end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_exam.rb
class BlogExam < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :content,    length: { in: 1..140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_exams_controller.rb
class BlogExamsController < ApplicationController
  before_action :set_blog_exam, only: [:show, :edit, :update, :destroy]

  def index
    @blog_exams = BlogExam.all
    #allで複数の値を入れるから複数形の命名
  end

  def new
    @blog_exam = BlogExam.new
  end

  def create
    @blog_exam = BlogExam.new(blog_exam_params)
    if params[:back]
      render :new
    else
      if @blog_exam.save
        redirect_to blog_exams_path, notice: "ブログを作成しました！"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end
  
  def update
    if @blog_exam.update(blog_exam_params)
      redirect_to blog_exams_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @blog_exam.destroy
    redirect_to blog_exams_path, notice: "ブログを削除しました！"
  end

  def confirm
    @blog_exam = BlogExam.new(blog_exam_params)
    render :new if @blog_exam.invalid?
  end

  private

  def blog_exam_params
    params.require(:blog_exam).permit(:title, :content)
  end

  def set_blog_exam
    @blog_exam = BlogExam.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_exams_helper.rb
module BlogExamsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blog_exams_path
    elsif action_name == 'edit'
      blog_exam_path
    end
  end
end

app/views/blog_exams/_form.html.erb
<%= form_with(model: @blog_exam, local: true, url: choose_new_or_edit ) do |form| %>
<% if @blog_exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog_exam.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog_exam.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_exam_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_exam_content"> 
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "ブログ一覧画面に戻る", blog_exams_path %>

app/views/blog_exams/confirm.html.erb
<h3>以下の内容で送信する。</h3>

<%= form_with(model: @blog_exam, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @blog_exam.title %></p>
  <p>本文:<%= @blog_exam.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit  "戻る", name: 'back' %>
<% end %>

app/views/blog_exams/edit.html.erb
<h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/blog_exams/index.html.erb
<h1>ブログ一覧</h1>

<p><%= notice %></p>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

<% @blog_exams.each do |blog_exam| %>
  <tr>
    <td><%= blog_exam.title %></td>
    <td><%= blog_exam.content %></td>
    <td><%= link_to '詳細を確認する', blog_exam_path(blog_exam.id) %></td>
    <td><%= link_to "ブログを編集する", edit_blog_exam_path(blog_exam.id) %></td>
    <td><%= link_to 'ブログを削除する', blog_exam_path(blog_exam.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to '新しくブログを投稿する', new_blog_exam_path %>

app/views/blog_exams/new.html.erb
<h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/blog_exams/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog_exam.title %></p>
<p>内容: <%= @blog_exam.content %></p>
<%= link_to "ブログ一覧画面に戻る", blog_exams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogexam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>